# Generated by Django 5.2.12 on 2026-04-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payappuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
    ]
