# Generated by Django 5.2.12 on 2026-04-04 15:00
from django.contrib.auth.hashers import make_password

from django.db import migrations


#register an administrative user upon activating the model
#with username: 'admin1', password:'admin1'
def generate_admin1(apps, schema_editor):
    User = apps.get_model('register', 'PayAppUser')
    #if the admin1 user already exists dont overwrite!
    if not User.objects.filter(username='admin1').exists():

        user = User()
        user.username = 'admin1'
        user.password = make_password('admin1')
        user.is_staff = True
        user.is_superuser = True
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_payappuser_balance'),
    ]

    operations = [
        migrations.RunPython(generate_admin1)
    ]

