# Generated by Django 5.2.12 on 2026-04-22 12:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('payer_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'Great British Pound')], default='EUR', max_length=3)),
                ('payee_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('payee_currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'Great British Pound')], default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'REJECTED')], default='REJECTED', max_length=10)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payee', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
